### ISSUE TITLE
西瓜视频记录里有收到推送通知栏里不通知

### ISSUE THREAD

**Issue by landenzhang** [NihilityT/MiPushFramework#1]
推送服务为：0817版本，手机为k20pro,刷的类原生android12.1系统。
问题：
⒈西瓜视频已经提示注册成功，记录里也有收到的推送消息记录，但是通知栏不显示；
log如下：
Developer Info:
XmPushActionContainer(action:SendMessage, encryptAction:true, isRequest:false, pushAction:08 00 01 00 00 00 05 02 00 02 01 02 00 03 00 0B 00 04 00 00 02 F0 E5 99 85 16 51 9D 99 CA 6F A6 D0 5E 09 97 E6 92 2D F4 D8 5E 5F FD 0A A1 43 BD 57 46 EE FC 60 D4 52 86 85 ED 25 E9 23 96 E1 B0 75 A5 38 05 D9 3D 95 73 1E 95 2B 3D BA D4 26 CD FF F1 FC B0 21 99 27 A5 FF C0 7D 2A FC 9A CD 2E B5 D4 B3 4D 08 D6 45 FC E7 E5 EA 14 EE E0 05 D1 A5 22 BB A2 7F 4B 1E C7 7C 0C D2 C1 C4 6F A1 6E..., appid:2882303761517484698, packageName:com.ss.android.article.video, target:Target(channelId:5, userId:72892661408, server:xiaomi.com, resource:anfbO7Ix), metaInfo:PushMetaInfo(id:adm61704661505317818bY, messageTs:1661505317820, title:西瓜视频, description:北京颐和园发现慈禧本人画像，这才是真实相貌，和想象中差别太大, notifyType:0, passThrough:1, notifyId:0, extra:{__check_alive=true, __target_name=1412237446099757, fe_ts=1661505317818, callback.type=241, notification_style_type=1, callback=http://i.snssdk.com/cloudpush/callback/mipush/?appid=32&rid=23861761, __m_ts=1661505318216, __awake=false}, ignoreRegInfo:false))
![Screenshot_20220826-162358_推送服务](https://user-images.githubusercontent.com/51550418/186871946-71f8ee16-e059-4891-a9e1-e8ab18d1bf3f.png)
![Screenshot_20220826-162405_推送服务](https://user-images.githubusercontent.com/51550418/186871999-fcffc231-381b-49d3-8973-89a4f748675b.png)
⒉酷安app每次打开都提示注册成功，但收不到任何推送。

**Comment by NihilityT** [comment]
1、通知中存在 passThrough:1，说明是直接发给应用的，不会显示通知，非 BUG。
参考：https://dev.mi.com/console/doc/detail?pId=1278#_2_0 3.1.1

2、是否推送消息由应用决定，无法控制。
