### ISSUE TITLE
小米12mipush一直注册服务未成功

### ISSUE THREAD

**Issue by 1001ace1001** [NihilityT/MiPushFramework#20]
**Describe the bug/**
A clear and concise description of what the bug is.（解释一下出了什么问题）
系统环境：a13-miui14
mipush一直注册服务未成功 一点记录并刷新就卡在那里转圈圈
**To Reproduce**
Steps to reproduce the behavior:（如何复现错误，也就是您的操作步骤）
1. 恢复系统推送服务为出厂版本
2. 刷入精简模块
3. 启动mipush并给予需要权限
4. 删除基本上所有的mipush.xml
5. 重启应该自动注册的应用
6. 错误复现，应用一直注册mipush失败
**Expected behavior**
A clear and concise description of what you expected to happen.（您希望发生什么）
他应该成功注册而且推送通知
**Screenshots**（截图）
![image](https://github.com/NihilityT/MiPushFramework/assets/100484574/b959c3a1-da32-4d82-88d6-8514b2643a8e)

**Logs** （日志）
Logs are very important, this can help us solve the problem.
Please upload your log file and paste the address here:（请上传您的日志文件，在这里粘贴地址：）
[logs-2023-48-23-21-48-59.zip](https://github.com/NihilityT/MiPushFramework/files/11544828/logs-2023-48-23-21-48-59.zip)

**ROM and version(manager):** （你的 ROM 和 manager 的版本）
 - Name: [e.g. Lineage OS]    miui 14 stable cn 14.0.6
 - Android Version: [e.g. 8.1]   13
 - Version [e.g. 0.3.4 stable]    stable cn 14.0.6
 - magisk delta 25210+lsposed 6898
**Additional context**
Add any other context about the problem here.（更多关于问题的内容写在这里）
期待作者回复 且 mipush在另外一台miui的机器上工作正常
日志中有权限不足的提示，还有网络连接失败的提示，这让我很困惑
毕竟我在清除数据之后已经给予了全部必要的权限。甚至在卸载重装之后仍是如此
切换代理之后注册服务也无法连接

**Comment by NihilityT** [comment]
没有给 WIFI 权限，并且机器的网络环境有问题。
授予所有权限，并关闭除 mipush 之外的所有模块后重启机器再次尝试。
