### ISSUE TITLE
能否让工作资料里的应用也支持推送

### ISSUE THREAD

**Issue by gtfvool** [NihilityT/MiPushFramework#22]
我试着将应用克隆进工作资料里，但并不可用。

**Comment by DataEraserC** [comment]
@gtfvool 有没有把mipushframework也克隆进去？ 有没有保活克隆后的mipushframework？

**Comment by gtfvool** [comment]
> @gtfvool 有没有把mipushframework也克隆进去？ 有没有保活克隆后的mipushframework？

克隆进去了。
上次克隆进去后工作资料里使用mipush的app完全不显示，更别提注册了。
但是今天我又试了一次，又一切正常了。

**Comment by NihilityT** [comment]
> 我试着将应用克隆进工作资料里，但并不可用。

@gtfvool 工作资料指的是多开吗？最新版本 [v0.3.10](https://github.com/NihilityT/MiPushFramework/releases/tag/v0.3.10) 是否还有该问题？
