### ISSUE TITLE
网易支付APP注册和反注册

### ISSUE THREAD

**Issue by qiuyouxin** [NihilityT/MiPushFramework#23]
**Describe the bug/**

网易支付APP最新版，注册后再次打开网易支付后必反注册。

**To Reproduce**

手动注册后依然反注册，试过push多版本和模块都是如此。

**Expected behavior**

作者有空帮忙看下，怎么回事，是否能够修复支持网易支付APP。

**Logs** （日志）
[logs-2023-24-13-12-24-40.zip](https://github.com/NihilityT/MiPushFramework/files/12035677/logs-2023-24-13-12-24-40.zip)
[LSPosed_2023-07-13T12_21_25.392.zip](https://github.com/NihilityT/MiPushFramework/files/12035679/LSPosed_2023-07-13T12_21_25.392.zip)

**ROM and version(manager):** （你的 ROM 和 manager 的版本）

红米k30s-miui13-A12

**Comment by NihilityT** [comment]
此为应用自主行为，无法处理。
