### ISSUE TITLE
手机重启后推送服务应用被卸载了

### ISSUE THREAD

**Issue by PlantHwyaden** [NihilityT/MiPushFramework#26]
手机重启开机后，推送服务app被卸载了

设备：红米k40
miui版本：v14.0.2.3.4.17 DEV
已root设备

请问要如何解决这个问题呢？

**Comment by PlantHwyaden** [comment]
补充：已经通过爱搞机的应用管理将小米服务精简应用了

**Comment by NihilityT** [comment]
使用最新版本，直接核心破解安装。
