### ISSUE TITLE
安装MiPush模块后仅保留一个应用名称

### ISSUE THREAD

**Issue by Nep-Timeline** [NihilityT/MiPushFramework#27]
**Is your feature request related to a problem? Please describe.**（该功能是否与问题有关？请描述）
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]（简单描述问题所在）
问题在于标题中会有两个应用名称

**Describe the solution you'd like**（说一下您想解决什么问题，想要做什么）
![_8d18b3204806682051beda16a02ca051_247193200_IMG20230817142840](https://github.com/NihilityT/MiPushFramework/assets/53483352/0ff0fcbf-ddd6-4a60-917a-5f58ca84fa19)
安装MiPush模块后移除金色的QQ标题

**Comment by NihilityT** [comment]
使用配置文件解决此问题：[MiPushConfigurations](https://github.com/NihilityT/MiPushConfigurations)
