### ISSUE TITLE
希望提供root申请开关

### ISSUE THREAD

**Issue by UQJRlex** [NihilityT/MiPushFramework#3]
当前，只有首次安装app，才有出现root申请弹窗。

过去，有个“全局伪装”，可视作root申请开关。

如果因为某种原因（比如清除cache分区），magisk su掉了，即便重新刷回来，那些需要root权限的app仍然需要重新申请。

在过去，直接重新设置一下“全局伪装”就可以，现在不可能了。

如果卸载掉push app后重新安装，就能再次申请root权限，但更会产生注册异常的问题。

所以，希望出现这个root申请的设置选项。

**Comment by RedLeaf007** [comment]
没有那个必要了。
出于一些情况的考虑，framework本体没有提供伪装的必要
root后可以使用[MiPush Faker](https://github.com/yin-ol/MiPushFaker)
或者[MiPush Framework的分应用模块](https://github.com/NihilityT/MiPush)进行伪装。

**Comment by NihilityT** [comment]
没主动申请说明没需要，若有此需求，可自行执行以下命令来获取：
`su <推送服务的 UID> -c su`
