### ISSUE TITLE
feature request: 隐藏正在运行通知

### ISSUE THREAD

**Issue by mio-19** [NihilityT/MiPushFramework#31]
**Is your feature request related to a problem? Please describe.**（该功能是否与问题有关？请描述）
不想看到這個通知

**Describe the solution you'd like**（说一下您想解决什么问题，想要做什么）
增加一个选项

**Describe alternatives you've considered**（简要描述您考虑过的替代方案）
N/A

**Additional context**
Add any other context or screenshots about the feature request here.（更多需要告诉我们的内容）

**Comment by NihilityT** [comment]
指南有写怎么关闭。
