### ISSUE TITLE
配置文件目录消失

### ISSUE THREAD

**Issue by littleli233** [NihilityT/MiPushFramework#32]
**Describe the bug/**
配置文件目录被删除

**To Reproduce**
Steps to reproduce the behavior:（如何复现错误，也就是您的操作步骤）
1. 下载官方图标配置文件
2. 复制到配置文件目录下的icon文件夹
3. 静置一段时间配置文件目录消失

**Expected behavior**
A clear and concise description of what you expected to happen.（您希望发生什么）
修复该bug

**Screenshots**（截图）

**Logs** （日志）
Logs are very important, this can help us solve the problem.
Please upload your log file and paste the address here:（请上传您的日志文件，在这里粘贴地址：）
[logs-2024-45-05-8-45-55.zip](https://github.com/NihilityT/MiPushFramework/files/13836799/logs-2024-45-05-8-45-55.zip)

**ROM and version(manager):** （你的 ROM 和 manager 的版本）
 - Name: oneui 4.1
 - Android Version: 12
 - Version 0.3.11-16 alpha

**Additional context**
Add any other context about the problem here.（更多关于问题的内容写在这里）

**Comment by NihilityT** [comment]
大概率是被其他应该给清理了。
尝试创建 /sdcard/Download/mipush 目录，将配置目录设为该目录，确认是否还会被删除。

**Comment by littleli233** [comment]
> 大概率是被其他应用给清理了。 尝试创建 /sdcard/Download/mipush 目录，将配置目录设为该目录，确认是否还会被删除。

可以了，谢谢
