### ISSUE TITLE
不要强制用户关闭电池优化

### ISSUE THREAD

**Issue by RichardLuo0** [NihilityT/MiPushFramework#39]
**Is your feature request related to a problem? Please describe.**（该功能是否与问题有关？请描述）
现在打开app会强制要求用户关闭电池优化 不然就退出了 我觉得这应该是可选的

**Describe the solution you'd like**（说一下您想解决什么问题，想要做什么）
可以提示一下用户 要关闭电池优化 但是不要做成强制要求 我自己clone下来改了改 编译了一个，开电池优化的情况下也没什么问题

**Comment by xj233168** [comment]
我也遇到了这种情况，我无法进入手机的电池优化页面

**Comment by xj233168** [comment]
> **Is your feature request related to a problem? Please describe.**（该功能是否与问题有关？请描述） 现在打开app会强制要求用户关闭电池优化 不然就退出了 我觉得这应该是可选的
> 
> **Describe the solution you'd like**（说一下您想解决什么问题，想要做什么） A clear and concise description of what you want to happen. 可以提示一下用户 要关闭电池优化 但是不要做成强制要求 我自己clone下来改了改 编译了一个，开电池优化的情况下也没什么问题

大佬，我不知道该怎么编译一个包，你可以把你编译好的包给我试试吗？

**Comment by RichardLuo0** [comment]
没空。。。而且我还没有Android 15

**Comment by NihilityT** [comment]
不开启电池优化会影响推送服务保活能力，可以参考以下官方文档：
- https://developer.android.com/reference/android/app/Service#startForeground(int,%20android.app.Notification)
  >  If your service is started (running through [Context.startService(Intent)](https://developer.android.com/reference/android/content/Context#startService(android.content.Intent))), then also make this service run in the foreground, supplying the ongoing notification to be shown to the user while in this state. By default started services are background, meaning that their process won't be given foreground CPU scheduling (unless something else in that process is foreground) and, if the system needs to kill them to reclaim more memory (such as to display a large page in a web browser), they can be killed without too much harm. You use [startForeground(int, Notification)](https://developer.android.com/reference/android/app/Service#startForeground(int,%20android.app.Notification)) if killing your service would be disruptive to the user, such as if your service is performing background music playback, so the user would notice if their music stopped playing.

- https://developer.android.com/develop/background-work/services/fgs/launch?hl=zh-cn#fgs-prerequisites
  > 以 Android 12（API 级别 31）或更高版本为目标平台的应用不得在后台运行时启动前台服务，但少数特定情况除外。如需了解详情以及此规则的例外情况，请参阅[与从后台启动前台服务相关的限制](https://developer.android.com/develop/background-work/services/fgs/restrictions-bg-start?hl=zh-cn)。

- https://developer.android.com/develop/background-work/services/fgs/restrictions-bg-start?hl=zh-cn
  > # 不受后台启动限制
  >  - 用户为您的应用关闭了电池优化。


目前没有精力做配置，暂时不会考虑该需求，如果你能重构代码让权限申请又漂亮又可配置的话，欢迎 PR。

**Comment by RichardLuo0** [comment]
不需要啊 有那个前台通知就够了呀 就是通知面板里会显示后台应用 我目前android14 15 都用的我自己编译的没有电池优化的 没遇到过掉后台的问题
