### ISSUE TITLE
升级到20221026显示应用自身注册异常，功能不受影响

### ISSUE THREAD

**Issue by boilfish** [NihilityT/MiPushFramework#5]
![Screenshot_20221029-090816_推送服务](https://user-images.githubusercontent.com/42105129/198766391-5b9c63fa-fe0d-4874-8a24-e25e46ed94a6.png)
从0.3.7.20220928.6de1a204升级至0.3.7.20221026.92d4eb92显示自身注册异常，其他应用推送功能不受影响，尝试重启手机无效

按照faq中指引清除com.xiaomi.xmsf的/data/data…mipush.xml并重启手机后问题解决，如果为个例请忽略

系统:PixelOS Android 12.1

**Comment by blxueya** [comment]
不是个例，且我的推送功能收影响

**Comment by NihilityT** [comment]
该改动仅用于展示推送服务注册状态，用于确认能否请求网络成功，不影响使用。
